# Generated by Django 3.2.4 on 2021-06-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_current_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_save',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
